name: "Validate Type coverage"
on: [push]

jobs:
  test-coverage:
    name: "Check TypeScript coverage"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: "Install dependencies"
        run: npm install
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - uses: LouisBrunner/checks-action@v1.1.1
        name: "Start status check"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: TypeScript coverage reporter
          status: in_progress
          output: |
            {"summary": "Waiting for the response from reporter"}
      - id: coverage
        name: "Run coverage reporter"
        run: node ./scripts/checkCoverage.js
        env:
          GITHUB_BRANCH: ${{ env.GITHUB_REF_SLUG }}
          GITHUB_MAIN_BRANCH: 'main'
          ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: LouisBrunner/checks-action@v1.1.1
        name: "Complete status check"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: TypeScript coverage reporter
          status: completed
          conclusion: ${{ steps.coverage.outputs.status }}
          output: |
            {"summary":${{ steps.coverage.outputs.message }}}
