name: "Validate Type coverage"
on: [push]

jobs:
  test-coverage:
    name: "Check TypeScript coverage"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: "Install dependencies"
        run: npm install
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - id: coverage
        name: "Run coverage reporter"
        run: node ./checkCoverage.js
        env:
          GITHUB_BRANCH: ${{ env.GITHUB_REF_SLUG }}
          GITHUB_MAIN_BRANCH: 'main'
          JSON_BIN_ID: ${{ secrets.JSON_BIN_ID }}
          JSON_SECRET_KEY: ${{ secrets.JSON_SECRET_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
